Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "nginx-82-HW8"
    vb.memory = 1024
    vb.cpus   = 1
  end

# Викоання bash скрипту
  config.vm.provision "shell", path: "setup_vm.sh"
end
