Vagrant.configure("2") do |config|

  config.vm.define "jenkins-master" do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.hostname = "jenkins-master"
    master.vm.network "private_network", ip: "192.168.56.10"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end

    master.vm.provision "shell", inline: <<-SHELL
      set -e

      apt-get update
      apt-get install -y ca-certificates curl gnupg lsb-release openjdk-17-jdk docker.io git wget

      systemctl enable docker
      systemctl start docker

      usermod -aG docker vagrant

      # Jenkins repository (FIXED GPG KEY METHOD)
      install -m 0755 -d /etc/apt/keyrings
      wget -q -O /etc/apt/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
      chmod a+r /etc/apt/keyrings/jenkins-keyring.asc

      echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list

      apt-get update
      apt-get install -y jenkins

      systemctl enable jenkins
      systemctl start jenkins
    SHELL
  end


  config.vm.define "jenkins-worker" do |worker|
    worker.vm.box = "ubuntu/jammy64"
    worker.vm.hostname = "jenkins-worker"
    worker.vm.network "private_network", ip: "192.168.56.11"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end

    worker.vm.provision "shell", inline: <<-SHELL
      set -e

      apt-get update
      apt-get install -y openjdk-17-jdk docker.io git

      systemctl enable docker
      systemctl start docker

      usermod -aG docker vagrant
    SHELL
  end

end

